# .streamlit/secrets.toml


[server]
sslCertFile = '/path/to/certchain.pem'
sslKeyFile = '/path/to/private.key'


[connections.tidb]
dialect = 'mysql'
host = 'gateway01.eu-central-1.prod.aws.tidbcloud.com'
port = 4000
database = 'pets'
username = '4NAru5SmcUg2Lu8.root'
password = 'Z9W4I9lsAzSiPxLC'
ssl_ca = '/path/to/certchain.pem'