# .streamlit/secrets.toml


[connections.tidb]
dialect = 'mysql'
host = 'gateway01.eu-central-1.prod.aws.tidbcloud.com'
port = 4000
database = 'pets'
username = '4NAru5SmcUg2Lu8.root'
password = 'Z9W4I9lsAzSiPxLC'
